POST http://localhost:3000/api/employee/addEmployee
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Smith",
  "email": "janesmith@example.com",
  "gender": "Female",
  "dob": "1988-05-23",
  "phone": "0767548486",
  "address": "456 Elm Street",
  "role": "Chef"
}

###
PUT http://localhost:3000/api/employee/editEmployee
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Doe",
  "email": "janedoe@example.com",
  "gender": "Female",
  "dob": "1988-06-30",
  "phone": "0767548486",
  "address": "789 Oak Street",
  "role": "Manager"
}
