GET http://localhost:3000/api/restaurant

###
PUT http://localhost:3000/api/restaurant/updatetable/20

###
GET http://localhost:3000/api/table/init

###
GET http://localhost:3000/api/table/6600f10fc60ab3558449d822

<> 2024-03-25T113205.200.json


###
PUT http://localhost:3000/api/table/updateStatus/6600f10fc60ab3558449d822
Content-Type: application/json

{
  "status": "ACTIVE"
}


###
PUT http://localhost:3000/api/table/open/6600f10fc60ab3558449d822

###
PUT http://localhost:3000/api/table/swap
Content-Type: application/json

{
  "tableId1": "6600f10fc60ab3558449d822",
  "tableId2": "6600f10fc60ab3558449d821"
}

###
PUT http://localhost:3000/api/order/addItem/6603be81a226c772a821da46
Content-Type: application/json

{
  "items": [
    {
      "itemId": "65feddc9e146f5d58d090dbd",
      "quantity": 2
    },
    {
      "itemId": "65fee0185a147406b7e69eb4",
      "quantity": 1
    }
  ]
}
